//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vaccineTracer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegister
    {
        public int Reg_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string cnic { get; set; }
        public Nullable<int> age { get; set; }
        public string city { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
    }
}
